config/routes.rb
Rails.application.routes.draw do
  get "home/index"

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users do
      member do
          get 'profile'
          get 'account'
       end  
  end

  resources :sessions
  
  resources :subscriptions
  resources :plans
  
  root 'home#index'

  resources :home do
        collection do
          get 'dashboard'
         end  
  end
          
  resources :password_resets

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_one :subscription
  has_one :plan, :through => :subscription
  
  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validate :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX 

  has_many :images, :as => :event, :dependent => :destroy, finder_sql: proc { "select DISTINCT b.* FROM images b INNER JOIN
users v ON b.event_id = v.id WHERE b.event_type ='User' AND b.event_id = #{self.id} and b.lock_version <> -1"}

  has_many :spoken_languages
  accepts_nested_attributes_for :spoken_languages, :allow_destroy => true

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "main_layout"
  def new
    @user = User.new
  end

  def create
    params.permit!
    @user = User.new(params[:user])
    if params[:add_spoken_language]
      # add empty language associated with @user
      @user.spoken_languages.build
    elsif params[:remove_spoken_language]
      # nested model that have _destroy attribute = 1 automatically deleted by rails
    else
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_url, notice: "Thank you for signing up!" and return
      # else
      end
    end
    render "new"  
  end

  def edit
    @user = User.find(params[:id])
    @user.spoken_languages.build if @user.spoken_languages.blank?
  end
    
  def show
    @user = current_user
  end

  def update
    params.permit!
    @user = current_user
    if params[:add_spoken_language]
      # rebuild the spoken_language attributes that doesn't have an id
      unless params[:user][:spoken_languages_attributes].blank?
          for attribute in params[:user][:spoken_languages_attributes]
            @user.spoken_languages.build(attribute.last.except(:_destroy)) unless attribute.last.has_key?(:id)
          end
      end
      # add one more empty spoken language attribute
      @user.spoken_languages.build
      render "edit"
    elsif params[:remove_spoken_language]
      # collect all marked for delete spoken_language ids
      removed_spoken_languages = params[:user][:spoken_languages_attributes].collect { |i, att| att[:id] if (att[:id] && att[:_destroy].to_i == 1) }
      # physically delete the spoken languages from database
      SpokenLanguage.delete(removed_spoken_languages)
      flash[:notice] = "spoken_languages removed."
      for attribute in params[:user][:spoken_languages_attributes]
        # rebuild spoken_language attributes that doesn't have an id and its _destroy attribute is not 1
        @user.spoken_languages.build(attribute.last.except(:_destroy)) if (!attribute.last.has_key?(:id) && attribute.last[:_destroy].to_i == 0)
      end
      render "edit"
    else
        flash[:notice] = @user.update_attributes(params[:user]) ? "Profile Successfully updated" : "Problem with profile update"
        images = @user.images
        if images.length > 0
          @image = images[0]
          @image.update_attributes(:photo => params[:photo]) if params[:photo]
        else
          @image = Image.create(:photo => params[:photo], :event_type => @user.class.to_s, :event_id => @user.id) if params[:photo]
        end
        render "show"
     end   
     
  end
    
  def profile
    @user = current_user
    render layout: "dashboard_layout"
  end  
  
  def account
    @user = current_user
    render layout: "dashboard_layout"
  end  

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,:first_name,:last_name, :company_name, :about_you, :country, :location, :billing_address, :highest_education, :open_for_work, :school_name, :job_title, :github_account, :dribble_account, :linkedin_account, :twitter_account, :facebook_account, :google_account, :reddit_account, :website_url)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account.html.erb
<aside data-layout-element="sidebar" style="display:block;">
      <select id="nav-list-select">
          <option value="/account" selected>Profile Info</option>
          <option value="/account/subscription" >Enrollment</option>
          <option value="/account/billing" >Billing History</option>
          <option value="/account/users" >Group Members</option>
          <option value="/account/notifications" >Email Notifications</option>
          <option value="/account/referrals" >Referrals</option>
          <option value="/account/privacy" >Privacy Settings</option>
      </select>
      <ul id="sidebar-nav">
          <li
            class="current "
            >
              <%= link_to "Profile Info", account_user_path(current_user), :onclick=>"javascript:void(0);" %> 
          </li>
          <li
            class=" "
            >
              <a href="#">Enrollment</a>
          </li>
          <li
            class=" "
            >
              <a href="#">Billing History</a>
          </li>
          <li
            class=" "
            >
              <a href="#">Group Members</a>
          </li>
          <li
            class=" "
            >
              <a href="#">Email Notifications</a>
          </li>
          <li
            class=" "
            >
              <a href="#">Referrals</a>
          </li>
          <li
            class=" "
            >
              <a href="#">Privacy Settings</a>
          </li>
      </ul>
    

  </aside>

   <div id="content" class="" style="width:70% !important;">
  

  

    <div class="grid-container">
    <div class="grid-100">
      <div class="contained">
        <div class="grid-100">
          <dl>
            <!--
              <div class="data-item">
                <dt class="grid-100 grid-parent">
                  <div class="avatar">
                    <img src="https://secure.gravatar.com/avatar/b203c2fbe27dc9f5b94119bac0921845?s=200&amp;d=https%3A%2F%2Fstatic.teamtreehouse.com%2Fassets%2Fcontent%2Fdefault_avatar-da0d43531e2db7455dc68b8f80e7dc21.png&amp;r=pg" />
                  </div>
                </dt>
              </div>
            -->

            <div class="data-item">
              <dt class="grid-25 grid-parent">First Name</dt>
              <dd class="grid-75 grid-parent"><%= @user.first_name %></dd>
            </div>

            <div class="data-item">
              <dt class="grid-25 grid-parent">Last Name</dt>
              <dd class="grid-75 grid-parent"> <%= @user.last_name %></dd>
            </div>

            <div class="data-item">
              <dt class="grid-25 grid-parent">Email Address</dt>
              <dd class="grid-75 grid-parent"><%= @user.email %></dd>
            </div>

            <div class="data-item">
              <dt class="grid-25 grid-parent">Password</dt>
              <dd class="grid-75 grid-parent">&#8226; &#8226; &#8226; &#8226; &#8226; &#8226; &#8226; &#8226;</dd>
            </div>


              <div class="data-item">
                <dt class="grid-25 grid-parent">Treehouse Profile URL</dt>
                <dd class="grid-75 grid-parent"><span class="light"><%= @user.website_url %>/</span><%= @user.first_name %></dd>
              </div>

              <div class="data-item">
                <dt class="grid-25 grid-parent">About You</dt>
                <dd class="grid-75 grid-parent"><%= @user.about_you %></dd>
              </div>

              <div class="data-item">
                <dt class="grid-25 grid-parent">Company</dt>
                <dd class="grid-75 grid-parent"><%= @user.company_name %></dd>
              </div>

              <div class="data-item">
                <dt class="grid-25 grid-parent">Job</dt>
                <dd class="grid-75 grid-parent"><%= @user.job_title %></dd>
              </div>

              <div class="data-item">
                <dt class="grid-25 grid-parent">Billing Address</dt>
                <dd class="grid-75 grid-parent"><%= @user.billing_address %></dd>
              </div>

              <div class="data-item">
                <dt class="grid-25 grid-parent">Country</dt>
                <dd class="grid-75 grid-parent"><%= @user.country %></dd>
              </div>

              <div class="data-item">
                <dt class="grid-25 grid-parent">Location</dt>
                <dd class="grid-75 grid-parent"><%= @user.location %></dd>
              </div>

              <div class="data-item">
                <dt class="grid-25 grid-parent">Looking for work?</dt>
                <dd class="grid-75 grid-parent">
                  <%= @user.open_for_work %>
                </dd>
              </div>

              <div class="data-item">
                <dt class="grid-25 grid-parent">Spoken Languages</dt>
                <dd class="grid-75 grid-parent"><%= @user.spoken_languages.map(&:name).join(",") %> </dd>
              </div>






              <div class="data-item">
                <dt class="grid-25 grid-parent">GitHub Profile</dt>
                <dd class="grid-75 grid-parent"><a href="#"><%= @user.github_account %></a></dd>
              </div>


              <div class="data-item last">
                <dt class="grid-25 grid-parent">LinkedIn Profile</dt>
                <dd class="grid-75 grid-parent"><a href="#"> <%= @user.linkedin_account %></a></dd>
              </div>

              <div class="data-item last">
                <dt class="grid-25 grid-parent">Website</dt>
                <dd class="grid-75 grid-parent"><a href="#"><%= @user.website_url %></a></dd>
              </div>

          </dl>
          <div class="form-footer">
             <%= link_to 'Edit Account', edit_user_path(@user), :class => "button primary" %>
            <a class="button secondary" href="#">Change Password</a>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/users/edit.html.erb
<div class="index signup-form">
                <div class="row">
                    <div class="container header_banner">
                        <h3><%= flash[:notice] %></h3>
                        <h1></h1>
                        <div class="visible-xs">
                            <br />
                            <br />
                        </div>
                        <div class="col-xs-12 col-sm-10 col-sm-offset-1 round-corners">
                            <a href="#" class="list-group-item active"> <%= current_user.first_name if current_user %> Profile</a>
                            <%= form_for @user, :method => :put, :html => { :multipart => true } do |f| %>
                              <% if @user.errors.any? %>
                                <div class="error_messages">
                                  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this subscription from being saved:</h2>
                                  <ul class="pull-left">
                                  <% @user.errors.full_messages.each do |msg| %>
                                    <li ><%= msg %></li>
                                  <% end %>
                                  </ul>
                                </div>
                                <br />
                              <% end %>

                            <div class="form-container">
                                <h2>
                                    <span>1</span>
                                    Your Information
                                </h2>
                                <br />
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <%= display_user_image(@user, "large") %>
                                 </div>   
                                <div class="col-xs-12 col-sm-6 col-md-8">
                                    <%= file_field_tag 'photo' %>
                                </div>
                                <div class="hidden-sm">
                                    <div class="clear"></div>
                                    <br />
                                </div>
                                <br />
                                <div class="clear"></div>
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    
                                    <%= f.text_field :first_name, :class=>"form-control", :placeholder=>"First Name"  %>
                                </div>
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <%= f.text_field :last_name, :class=>"form-control", :placeholder=>"Last Name"  %>
                                </div>
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <%= f.text_field :email, :class=>"form-control", :placeholder=>"Email"  %>
                                </div>
                                 <div class="hidden-sm">
                                    <div class="clear"></div>
                                    <br />
                                </div>
                                <div class="col-xs-12 col-sm-6 col-md-12">
                                    <!-- <input type="text" class="form-control" placeholder="Company Name" /> -->
                                    <%= f.text_area :about_you, :class=>"form-control", :placeholder=>"About you"  %>
                                </div>
                                 <div class="hidden-sm">
                                    <div class="clear"></div>
                                    <br />
                                </div>
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <%= f.select :country, ["USA","UK","Australia","China","South Africa"], {prompt: 'Please select country' } %>
                                </div>
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <%= f.text_field :location, :class=>"form-control", :placeholder=>"Location"  %>
                                </div>
                                <div class="hidden-sm">
                                    <div class="clear"></div>
                                    <br />
                                </div>
                                <div class="col-xs-12 col-sm-6 col-md-12">
                                    <%= f.text_area :billing_address, :class=>"form-control", :placeholder=>"Billing Address"  %>
                                </div>
                                <div class="clear"></div>
                                <hr />
                                <h2>
                                    <span>2</span>
                                    Education/Professional detail
                                </h2>
                                <br />
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                     <%= f.select :highest_education, ["Doctrate","Medical","Post graduate","Graduate","High School"], {prompt: 'Highest Level of Education' } %>
                                </div>
                                
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <%= f.select :open_for_work, ["Yes","No"], {prompt: 'I am looking for work' } %>
                                </div>
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <%= f.text_field :school_name, :class=>"form-control", :placeholder=>"School Name"  %>
                                </div>
                                 <div class="hidden-sm">
                                    <div class="clear"></div>
                                    <br />
                                </div>
                                <div class="visible-xs">
                                    <div class="clear"></div>
                                    <br />
                                </div>
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <%= f.text_field :company_name, :class=>"form-control", :placeholder=>"Company Name"  %>
                                </div>
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <%= f.text_field :job_title, :class=>"form-control", :placeholder=>"Job Title"  %>
                                </div>
                                <div class="hidden-sm">
                                    <div class="clear"></div>
                                    <br />
                                </div>
                                <div class="visible-xs">
                                    <div class="clear"></div>
                                    <br />
                                </div>
                                
                                <% l_cnt = 1 %>
                                <%= f.fields_for :spoken_languages do |ing| %>
                                    <div class="col-xs-12 col-sm-6 col-md-8">
                                      <%= ing.text_field :name, :class=>"form-control", :placeholder=>"spoken language"  %>
                                    </div>
                                    <% if l_cnt != 1 %>
                                    <div class="col-xs-12 col-sm-6 col-md-1">  
                                      <%= ing.check_box :_destroy %>
                                    </div>
                                    <div class="col-xs-12 col-sm-6 col-md-3">  
                                      <%= ing.label :_destroy, 'select to delete' %>
                                    </div>  
                                    <% end %>
                                    <% l_cnt+=1 %>
                                    <div class="hidden-sm">
                                    <div class="clear"></div>
                                    <br />
                                    </div>
                                    <div class="visible-xs">
                                        <div class="clear"></div>
                                        <br />
                                    </div>
                                <% end -%>
                                <div class="hidden-sm">
                                    <div class="clear"></div>
                                    <br />
                                </div>
                                <div class="visible-xs">
                                    <div class="clear"></div>
                                    <br />
                                </div>
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                </div> 
                                <div class="col-xs-12 col-sm-6 col-md-4">
                                    <%= f.submit 'Add Language', :name => "add_spoken_language",:class => "btn btn-lg pull-left" %>
                                </div>  
                                <div class="clear"></div>
                                <hr /> 
                                <h2>
                                    <span>3</span>
                                    Social Connect 
                                </h2>
                                <br />
                                <div class="col-xs-12 col-sm-4">
                                    <%= f.text_field :github_account, :class=>"form-control", :placeholder=>"Github connect"  %>
                                </div>
                                <div class="col-xs-12 col-sm-4">
                                    <%= f.text_field :dribble_account, :class=>"form-control", :placeholder=>"Dribble account"  %>
                                </div>
                                <div class="col-xs-12 col-sm-4">
                                    <%= f.text_field :linkedin_account, :class=>"form-control", :placeholder=>"Linkedin account"  %>
                                </div>
                                 <div class="hidden-sm">
                                    <div class="clear"></div>
                                    <br />
                                </div>
                                <div class="visible-xs">
                                    <div class="clear"></div>
                                    <br />
                                </div>
                                <div class="col-xs-12 col-sm-4">
                                    <%= f.text_field :twitter_account, :class=>"form-control", :placeholder=>"Twitter account"  %>
                                </div>
                                <div class="col-xs-12 col-sm-4">
                                    <%= f.text_field :facebook_account, :class=>"form-control", :placeholder=>"Facebook account"  %>
                                </div>
                                <div class="col-xs-12 col-sm-4">
                                    <%= f.text_field :google_account, :class=>"form-control", :placeholder=>"Google account"  %>
                                </div>
                                 <div class="hidden-sm">
                                    <div class="clear"></div>
                                    <br />
                                </div>
                                <div class="visible-xs">
                                    <div class="clear"></div>
                                    <br />
                                </div>
                                <div class="col-xs-12 col-sm-4">
                                    <%= f.text_field :reddit_account, :class=>"form-control", :placeholder=>"Reditt account"  %>
                                </div>
                                <div class="col-xs-12 col-sm-8">
                                    <%= f.text_field :website_url, :class=>"form-control", :placeholder=>"Website URL"  %>
                                </div>
                                <div class="clear"></div>
                                <hr />
                                
                                <div class="clear"></div>
                                <br />
                               
                                <div class="clear"></div>
                                <hr />
                                <!-- <button type="button" class="btn btn-lg btn-primary pull-left">Join Us Now</button> -->
                                <%= f.submit "Update Profile",:class => "btn btn-lg btn-primary pull-left" %>
                                
                                <div class="clear"></div>
                            </div>
                            <% end %>
                        </div>
                    </div>
                    <br />
                    <br />
                    <br />
                </div>        
            </div>

app/views/users/new.html.erb
<div class="index">
      <div class="row">
        <div class="container">
          <div class="col-md-12"> 
<div Style="margin:10px;width:400px;padding-top:50px;">
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br /><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br /><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br /><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <br />
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>
</div>
</div>
</div>
</div>
</div>