config/routes.rb
Rails.application.routes.draw do
  get "home/index"

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users do
      member do
          get 'profile'
          get 'account'
       end  
  end

  resources :sessions
  
  resources :subscriptions
  resources :plans
  
  root 'home#index'

  resources :home do
        collection do
          get 'dashboard'
         end  
  end
          
  resources :password_resets

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if current_user
  		  redirect_to :action=>'dashboard'
  	else
	  	render layout: "main_layout"
  	end
  end

  def dashboard
  	render layout: "dashboard_layout"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<footer>
    <svg class="logo-icon" preserveAspectRatio="xMinYMin meet" viewBox="0 0 30 32">
    <path d="M28.4,7.1c-0.4-0.2-1.3-0.6-2.3-1.2C25,5.3,23.3,6.3,22.2,8l-1.9,3.2c-0.7,1.4-0.6,2.9,0.3,4.2l0.1,0.1
        c0.9,1.3,2.1,2.4,2.4,2.8c0.2,0.2,0.4,0.6,0.5,0.9c0.3,1.2-0.3,2.3-1.5,2.6c-1.1,0.3-2.3-0.4-2.7-1.5c-0.1-0.3-0.1-0.6-0.1-0.9
        c0.1-0.5-0.1-1.3-0.8-1.9c-0.7-0.8-2.1,0.7-2.5,2.1v0.1c-0.4,1.5-0.7,2.7-0.6,2.8c0,0.1,0.1,0.2,0.1,0.2c0.6,1.2,0.2,2.6-1,3.2
        s-2.7,0.2-3.3-1s-0.2-2.6,1-3.2c0.1,0,0.1-0.1,0.2-0.1c0.1,0,0.3-0.7,0.6-1.4c0.2-0.7,0.4-1.3,0.4-1.3c0-0.1,0-0.2,0.1-0.2l1.2-4.2
        L13.5,17c-0.2-0.5-0.4-0.5-1-0.1c-0.3,0.2-0.9,0.7-1.1,0.9c-0.5,0.4-0.9,1.1-1.1,1.5c-0.1,0.3-0.3,0.5-0.5,0.7
        c-0.9,0.8-2.3,0.6-3-0.3s-0.5-2.1,0.4-2.8c0.3-0.2,0.6-0.4,0.9-0.4c0.5-0.1,2.4-1.3,3.5-2c0.2-0.1,0.4-0.3,0.5-0.4L15,12l-2.6,1.4
        c0,0-0.3,0-0.6,0c-0.8,0.1-1.8,0.2-2,0.5c-0.1,0.1-0.2,0.3-0.4,0.4c-0.8,0.4-2,0.2-2.7-0.6c-0.6-0.9-0.4-2,0.4-2.6
        c0.5-0.3,0.9-0.4,1.3-0.4c0.7,0,2.5,0.4,4,0.1l0.4-0.1c1.5-0.3,3.3-1.5,4-2.9c0,0,0.7-1.3,1.6-2.7c0.9-1.5,0.8-3.1-0.1-3.7l-1.7-1
        c-0.9-0.5-2.3-0.5-3.2,0L1.6,6.9C0.7,7.4,0,8.7,0,9.7v12.8c0,1,0.7,2.1,1.6,2.6l11.9,6.6c0.9,0.5,2.3,0.5,3.2,0L28.4,25
        c0.9-0.5,1.6-1.6,1.6-2.6V9.7C30,8.7,29.3,7.6,28.4,7.1z" />

</svg>
    <p>
      &copy;2015 Treehouse Island, Inc.
      <br>
      <a data-event-action="M: Clicked Blog" data-event-category="button" data-event-label="Source: Footer" data-featurette="analytics-click-event" href="#">Blog</a> &bull;
      <a data-event-action="M: Clicked Terms" data-event-category="button" data-event-label="Source: Footer" data-featurette="analytics-click-event" href="#">Terms</a> &bull;
      <a data-event-action="M: Clicked Privacy" data-event-category="button" data-event-label="Source: Footer" data-featurette="analytics-click-event" href="#">Privacy</a> &bull;
      <a data-event-action="M: Clicked Contact" data-event-category="button" data-event-label="Source: Footer" data-featurette="analytics-click-event" href="#">Contact</a>
    </p>
    <ul class="social">
      <li><a data-event-action="M: Clicked Twitter Icon" data-event-category="button" data-event-label="Source: Footer" data-featurette="analytics-click-event" href="#" target="_blank" title="Twitter"><svg class="twitter-icon" preserveAspectRatio="xMinYMin meet" viewBox="0 0 24 24"><use xlink:href="icons-91c15c7f0bde1fd321baa05087b71925.svg#twitter-icon"></use></svg></a></li>
      <li><a data-event-action="M: Clicked Youtube Icon" data-event-category="button" data-event-label="Source: Footer" data-featurette="analytics-click-event" href="#" target="_blank" title="Youtube"><svg class="youtube-icon" preserveAspectRatio="xMinYMin meet" viewBox="0 0 24 24"><use xlink:href="icons-91c15c7f0bde1fd321baa05087b71925.svg#youtube-icon"></use></svg></a></li>
      <li><a data-event-action="M: Clicked Facebook Icon" data-event-category="button" data-event-label="Source: Footer" data-featurette="analytics-click-event" href="#" target="_blank" title="Facebook"><svg class="facebook-icon" preserveAspectRatio="xMinYMin meet" viewBox="0 0 24 24"><use xlink:href="icons-91c15c7f0bde1fd321baa05087b71925.svg#facebook-icon"></use></svg></a></li>
      <li><a data-event-action="M: Clicked Google Plus Icon" data-event-category="button" data-event-label="Source: Footer" data-featurette="analytics-click-event" href="#" target="_blank" title="Google Plus"><svg class="google-plus-icon" preserveAspectRatio="xMinYMin meet" viewBox="0 0 24 24"><use xlink:href="icons-91c15c7f0bde1fd321baa05087b71925.svg#google-plus-icon"></use></svg></a></li>
      <li><a data-event-action="M: Clicked Linkedin Icon" data-event-category="button" data-event-label="Source: Footer" data-featurette="analytics-click-event" href="#" target="_blank" title="LinkedIn"><svg class="linked-in-icon" preserveAspectRatio="xMinYMin meet" viewBox="0 0 24 24"><use xlink:href="icons-91c15c7f0bde1fd321baa05087b71925.svg#linked-in-icon"></use></svg></a></li>
      <li><a data-event-action="M: Clicked Instagram Icon" data-event-category="button" data-event-label="Source: Footer" data-featurette="analytics-click-event" href="#" target="_blank" title="Instagram"><svg class="instagram-icon" preserveAspectRatio="xMinYMin meet" viewBox="0 0 24 24"><use xlink:href="icons-91c15c7f0bde1fd321baa05087b71925.svg#instagram-icon"></use></svg></a></li>
    </ul>
  </footer>

app/views/home/_footer_old.html.erb
             <footer>
                <img src="http://placehold.it/50X50" />
                <p>
                    ©2015 Company Name, Inc.
                    <br>
                    <a href="#">Blog</a> •
                    <a href="#">Terms</a> •
                    <a href="#">Privacy</a> •
                    <a href="#">Contact</a>
                </p>
                <ul class="social-menu">
                    <li><a href="#" target="_blank" title="Twitter"><i class="fa fa-twitter-square"></i></a></li>
                    <li><a href="#" target="_blank" title="Youtube"><i class="fa fa-youtube-square"></i></a></li>
                    <li><a href="#" target="_blank" title="Facebook"><i class="fa fa-facebook-square"></i></a></li>
                    <li><a href="#" target="_blank" title="Google Plus"><i class="fa fa-google-plus-square"></i></a></li>
                    <li><a href="#" target="_blank" title="Linkedin"><i class="fa fa-linkedin-square"></i></a></li>
                    <li><a href="#" target="_blank" title="Instagram"><i class="fa fa-instagram-square"></i></a></li>
                </ul>
                <div class="clear"></div>
            </footer>

app/views/home/_header.html.erb
 <nav data-layout-element="navigation">
    <section>
        <a href="#" class="brand" data-featurette="analytics-click-event" data-event-category="button" data-event-action="M: Clicked Treehouse Logo" data-event-label="Source: Navbar">
          <svg class="treehouse-icon" preserveAspectRatio="xMinYMin meet" viewBox="0 0 139 32">
  <g>
    <path class="icon-treehouse" d="M42.8,21c-0.4,0.1-0.9,0.2-1.4,0.2c-1,0-1.4-0.6-1.4-1.6v-4.5h2.8c0.7,0,1.4-0.5,1.4-1.3s-0.6-1.3-1.4-1.3
      H40V11c0-0.9-0.7-1.5-1.5-1.5S37,10.2,37,11v8.7c0,2.5,1.2,4.3,4,4.3c0.8,0,1.9-0.1,2.7-0.5c0.7-0.3,0.9-0.8,0.9-1.3
      C44.6,21.5,43.9,20.8,42.8,21z M52.8,12.1c-0.4-0.1-1.2-0.2-1.9-0.2c-2.5,0-3.9,1.5-3.9,3.8v6.8c0,0.8,0.7,1.5,1.5,1.5
      s1.5-0.7,1.5-1.5v-6.2c0-1,0.4-1.4,1.1-1.4c0.7,0,1.1,0.2,1.7,0.2c0.9,0,1.4-0.8,1.4-1.4C54.1,12.9,53.7,12.4,52.8,12.1z M61.1,11.9
      c-2.8,0-4.8,1.8-5.1,4.7c0,0.7-0.1,1.9,0,2.8c0.2,2.8,2.2,4.7,5.2,4.7c1.4,0,2.7-0.3,3.5-0.8c0.6-0.4,0.7-0.8,0.7-1.2
      c0-0.8-0.7-1.6-1.9-1.2c-0.7,0.3-1.5,0.5-2.3,0.5c-1.4,0-2.5-0.7-2.5-2.1V19h5.7c1,0,1.5-0.6,1.5-1.5V17C66,13.9,64,11.9,61.1,11.9z
       M63,17h-4.2c0-1.5,0.7-2.5,2.3-2.5c1.4,0,2.2,0.9,2.1,2.2C63.2,16.9,63.2,17,63,17z M73.1,11.9c-2.8,0-4.8,1.8-5.1,4.7
      c0,0.7-0.1,1.9,0,2.8c0.2,2.8,2.2,4.7,5.2,4.7c1.4,0,2.7-0.3,3.5-0.8c0.6-0.4,0.7-0.8,0.7-1.2c0-0.8-0.7-1.6-1.9-1.2
      c-0.7,0.3-1.5,0.5-2.3,0.5c-1.4,0-2.5-0.7-2.5-2.1V19h5.7c1,0,1.5-0.6,1.5-1.5V17C78,13.9,76,11.9,73.1,11.9z M75,17h-4.2
      c0-1.5,0.7-2.5,2.3-2.5c1.4,0,2.2,0.9,2.1,2.2C75.2,16.9,75.2,17,75,17z M123.6,16.9l-1.6-0.4c-1-0.2-1.3-0.5-1.3-1s0.5-0.9,1.6-0.9
      c0.6,0,1.3,0.2,1.9,0.5c0.7,0.4,1.5,0.3,1.9-0.2c0.5-0.5,0.5-1.4-0.1-2c-0.8-0.6-2.2-1-3.6-1c-2.6,0-4.5,1.3-4.5,3.7
      c0,1.9,1.4,2.9,3.2,3.4c0.9,0.2,0.8,0.2,1.6,0.4c0.9,0.2,1.3,0.6,1.3,1c0,0.6-0.5,1-1.7,1c-1,0-1.9-0.3-2.6-0.7
      c-0.7-0.5-1.5-0.3-1.9,0.3c-0.4,0.6-0.3,1.4,0.3,1.8c0.8,0.7,2.1,1.3,4.2,1.3c2.6,0,4.6-1.4,4.6-3.8
      C126.9,18.5,125.8,17.4,123.6,16.9z M137.5,19c1,0,1.5-0.6,1.5-1.5l0,0V17c0-3.1-2-5.1-4.9-5.1c-2.8,0-4.8,1.8-5.1,4.7
      c0,0.7-0.1,1.9,0,2.8c0.2,2.8,2.2,4.7,5.2,4.7c1.4,0,2.7-0.3,3.5-0.8c0.6-0.4,0.7-0.8,0.7-1.2c0-0.8-0.7-1.6-1.9-1.2
      c-0.7,0.3-1.5,0.5-2.3,0.5c-1.4,0-2.5-0.7-2.5-2.1V19H137.5z M134.1,14.5c1.4,0,2.2,0.9,2.1,2.2c0,0.2-0.1,0.3-0.2,0.3h-4.2
      C131.8,15.5,132.6,14.5,134.1,14.5z M97.5,11.9c-3,0-5.2,1.9-5.5,4.5c-0.1,0.9-0.1,2.3,0,3.2c0.2,2.6,2.5,4.5,5.5,4.5
      s5.2-1.9,5.4-4.5c0.1-0.9,0.1-2.2,0-3.1C102.7,13.8,100.5,11.9,97.5,11.9z M99.9,19.1c-0.1,1.3-1,2.1-2.4,2.1s-2.3-0.9-2.4-2.1
      c0-0.6,0-1.6,0-2.2c0.1-1.3,1-2.1,2.4-2.1s2.3,0.9,2.4,2.1C100,17.5,100,18.5,99.9,19.1z M85.6,11.9c-1.1,0-2.3,0.4-2.7,0.9l0,0V9.6
      c0-0.9-0.6-1.5-1.4-1.5s-1.4,0.7-1.4,1.5v12.9c0,0.8,0.7,1.5,1.5,1.5s1.4-0.7,1.4-1.5v-6.7c0.5-0.5,1.3-0.9,2.3-0.9
      c1.2,0,1.9,0.7,1.9,2.1v5.5c0,0.9,0.6,1.6,1.4,1.6c0.9,0,1.5-0.7,1.5-1.6v-5.7C90,13.6,88.4,11.9,85.6,11.9z M113.6,12
      c-0.8,0-1.5,0.7-1.5,1.5v7.1c-0.5,0.3-1.2,0.6-2.1,0.6c-1.2,0-2.1-0.7-2.1-2.1v-5.6c0-0.9-0.7-1.6-1.5-1.6c-0.9,0-1.4,0.7-1.4,1.6
      v5.7c0,3.1,1.8,4.8,4.9,4.8c2.3,0,3.9-0.8,4.6-1.3c0.4-0.2,0.5-0.5,0.5-1v-8.2C115,12.7,114.4,12,113.6,12z" />
    <path class="icon-logo" d="M28.4,7c-0.4-0.2-1.3-0.6-2.3-1.2c-1.1-0.6-2.8,0.4-3.9,2.1l-1.9,3.2c-0.7,1.4-0.6,2.9,0.3,4.2l0.1,0.1
      c0.9,1.3,2.1,2.4,2.4,2.8c0.2,0.2,0.4,0.6,0.5,0.9c0.3,1.2-0.3,2.3-1.5,2.6c-1.1,0.3-2.3-0.4-2.7-1.5c-0.1-0.3-0.1-0.6-0.1-0.9
      c0.1-0.5-0.1-1.3-0.8-1.9c-0.7-0.8-2.1,0.7-2.5,2.1v0.1c-0.4,1.5-0.7,2.7-0.6,2.8c0,0.1,0.1,0.2,0.1,0.2c0.6,1.2,0.2,2.6-1,3.2
      s-2.7,0.2-3.3-1s-0.2-2.6,1-3.2c0.1,0,0.1-0.1,0.2-0.1c0.1,0,0.3-0.7,0.6-1.4c0.2-0.7,0.4-1.3,0.4-1.3c0-0.1,0-0.2,0.1-0.2l1.2-4.2
      l-1.2,2.5c-0.2-0.5-0.4-0.5-1-0.1c-0.3,0.2-0.9,0.7-1.1,0.9c-0.5,0.4-0.9,1.1-1.1,1.5c-0.1,0.3-0.3,0.5-0.5,0.7
      c-0.9,0.8-2.3,0.6-3-0.3s-0.5-2.1,0.4-2.8c0.3-0.2,0.6-0.4,0.9-0.4c0.5-0.1,2.4-1.3,3.5-2c0.2-0.1,0.4-0.3,0.5-0.4l2.9-2.1l-2.6,1.4
      c0,0-0.3,0-0.6,0c-0.8,0.1-1.8,0.2-2,0.5c-0.1,0.1-0.2,0.3-0.4,0.4c-0.8,0.4-2,0.2-2.7-0.6c-0.6-0.9-0.4-2,0.4-2.6
      c0.5-0.3,0.9-0.4,1.3-0.4c0.7,0,2.5,0.4,4,0.1l0.4-0.1c1.5-0.3,3.3-1.5,4-2.9c0,0,0.7-1.3,1.6-2.7c0.9-1.5,0.8-3.1-0.1-3.7l-1.7-1
      c-0.9-0.5-2.3-0.5-3.2,0L1.6,6.8C0.7,7.3,0,8.6,0,9.6v12.8c0,1,0.7,2.1,1.6,2.6l11.9,6.6c0.9,0.5,2.3,0.5,3.2,0l11.7-6.7
      c0.9-0.5,1.6-1.6,1.6-2.6V9.6C30,8.6,29.3,7.5,28.4,7z" />
  </g>
</svg>
        </a>
        <a class="fixed-trial-button" href="#">Free trial</a>
      <div id="mobile-nav-toggle">
        <a href="#" id="nav-toggle" data-nav-toggle>
          <span class="hamburger"></span>
        </a>
      </div>
      <ul class="nav-list">
            <li class="nav-item nav-item-home ">
              <a class="nav-anchor" data-event-action="M: Clicked Home" data-event-category="button" data-event-label="Source: Navbar" data-featurette="analytics-click-event" href="#">Home</a>
            </li>
            <li class="nav-item ">
              <a class="nav-anchor" data-event-action="M: Clicked Features" data-event-category="button" data-event-label="Source: Navbar" data-featurette="analytics-click-event" href="#">Features</a>
            </li>
            <li class="nav-item ">
              <a class="nav-anchor" data-event-action="M: Clicked Stories" data-event-category="button" data-event-label="Source: Navbar" data-featurette="analytics-click-event" href="#">Stories</a>
            </li>
            <li class="nav-item ">
              <a class="nav-anchor" data-event-action="M: Clicked Plans" data-event-category="button" data-event-label="Source: Navbar" data-featurette="analytics-click-event" href="#">Pricing</a>
            </li>
            <li class="nav-item nav-item-sign-in" data-featurette="analytics-click-event" data-target="a" data-event-category: "button" data-event-action="M: Clicked Sign In" data-event-label="Source: Navbar">
               <% if current_user %>
                  <%= link_to "Log Out", logout_path, :class => "nav-anchor featurette"  %>
               <% else %>   
                <a class="nav-anchor featurette" data-featurette="modal-trigger" data-mobile-fallback="doit" data-target="login-modal" href="#">Sign in</a>
              <% end %>
            </li>
            <li class="nav-item nav-item-free-trial">
              <!-- <a class="nav-anchor" data-event-action="M: Clicked Free Trial" data-event-category="button" data-event-label="Source: Navbar" data-featurette="analytics-click-event" href="#">Free trial</a> -->
              <%= link_to "Free trial", plans_path, :class => "nav-anchor","data-event-action"=>"M: Clicked Free Trial", "data-event-category"=>"button", "data-event-label"=>"Source: Navbar", "data-featurette"=>"analytics-click-event"   %>
            </li>
      </ul>
    </section>
  </nav>

app/views/home/_header_old.html.erb
 <!--nav-->
            <nav class="navbar navbar-default navbar-custom" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="/"><%= image_tag asset_path('logo.png'),:height=>"40" %></a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li><a class="nav-link" href="#">Features</a></li>
                            <li><a class="nav-link" href="#">Stories</a></li>
                            <li><a class="nav-link" href="#">Pricing</a></li>
                             <% if current_user %>
                                <li id="user_header">  
                                   <span style="pull-left" ><%= display_user_image(current_user, "large") %> &nbsp;<span>
                                   <span style="pull-right;float:right"> 
                                     <%= link_to (current_user.first_name || current_user.email), user_path(current_user) %>
                                   </span>
                                </li>
                                <li>  <%= link_to "Log Out", logout_path, :class => "nav-link"  %></li>
                              <% else %>
                                <li> <%= link_to "Sign Up", plans_path, :class => "nav-link"  %> </li>
                                <li> <%#= link_to "Sign in", login_path, :class => "nav-link", "data-toggle"=>"modal", "data-target"=>"#myModal" %>  
                                    <a class="nav-link" href="#" data-toggle="modal" data-target="#myModal">Sign in</a>
                                </li>

                              <% end %>
                            <li><a class="nav-link" href="#" id="get-started">Get Started</a></li>
                        </ul>
                    </div>
                </div>
            </nav>

      <div Style="margin:10px;padding-top:30px;font-weight:600;">
      <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
    </div>
    <div id="myModal" class="modal fade" role="dialog">
      <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Sign in</h4>
          </div>
          <div class="modal-body login-form">
                 <%= form_tag sessions_path,:id => "signin_form" do %>
                <fieldset>
                    <div class="form-group">
                      <%= text_field_tag :email,params[:email], :class=>"form-control", :placeholder=>"E-mail" %>
                  </div>
                  <div class="form-group">
                    <%= password_field_tag :password,"",:class=>"form-control", :placeholder=>"Password" %>
                  </div>
                  <button class="btn btn-lg btn-success " type="submit" onclick="$('.signin_form').submit();">Login</button>
                  <%= submit_tag "Login",:class => "btn btn-lg btn-success",:style => "display:none;" %>
                    <span class="pull-right forgot">
                          <%= link_to "forgot password?", new_password_reset_path,:class => "" %>
                    </span>
                </fieldset>
                  <% end %>      
            </div>
        </div>
      </div>
    </div>