config/routes.rb
Rails.application.routes.draw do
  get "home/index"

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users do
      member do
          get 'profile'
          get 'account'
       end  
  end

  resources :sessions
  
  resources :subscriptions
  resources :plans
  
  root 'home#index'

  resources :home do
        collection do
          get 'dashboard'
         end  
  end
          
  resources :password_resets

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :subscriptions
  has_many :users
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  layout "main_layout_old"
  def index
    @plans = Plan.order("price")
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/index.html.erb
<div class="index signup-form">
                <div class="row">
                    <div class="container header_banner">
                        <h1>gschool Signup Plans</h1>
                        <div class="visible-xs">
                            <br />
                            <br />
                        </div>
                        <div class="col-xs-12 col-sm-10 col-sm-offset-1 round-corners">
                            <a href="#" class="list-group-item active"></a>
                           
                            <div class="form-container">
                                <% @plans.each do |plan| %>
                                        <div class="plan">
                                          <div class="name">
                                           <h2>
                                            <%= plan.name %>
                                          </h2>
                                          </div>
                                          <div class="details">
                                            <div class="price">
                                              <%= number_to_currency plan.price, :precision => 0 %> per month
                                            </div>
                                            <div class="kisses"><%= plan.description %> per month</div>
                                            <div class="">
                                              <%= link_to "Signup", new_subscription_path(:plan_id => plan.id),:class => "btn btn-lg btn-primary" %>
                                            </div>
                                          </div>
                                        </div>
                                        <hr />
                                      <% end %>
                                <div class="clear"></div>
                            </div>
                        </div>
                    </div>
                    <br />
                    <br />
                    <br />
                </div>        
            </div>